const STORAGE="gamevault-3d-games";const defaults=[{id:1,title:"NEON STRIKE",genre:"Action RPG",status:"Playing",hours:42,rating:9.2,color:0x5ee7ff,note:"Fast combat, neon cities, and a great progression loop."},{id:2,title:"VOID RUNNER",genre:"Sci-Fi Racing",status:"Completed",hours:28,rating:8.7,color:0x8b6cff,note:"High-speed racing across impossible orbital tracks."},{id:3,title:"EMBERFALL",genre:"Adventure",status:"Backlog",hours:4,rating:8.4,color:0xff775c,note:"A ruined kingdom hiding a strange ancient signal."},{id:4,title:"NIGHT OPS",genre:"Tactical",status:"Playing",hours:61,rating:9.0,color:0x65e6a5,note:"Methodical missions where every decision matters."},{id:5,title:"STARBOUND",genre:"Exploration",status:"Completed",hours:73,rating:9.5,color:0xffc65c,note:"A quiet journey through distant systems and lost worlds."},{id:6,title:"RIFT",genre:"Roguelike",status:"Backlog",hours:11,rating:8.5,color:0xe66ac9,note:"Every run reshapes the world and your build."}];let games=JSON.parse(localStorage.getItem(STORAGE)||"null")||defaults;let scene,camera,renderer,raycaster,mouse,roomGroup,gameMeshes=[],targetRotY=0,targetRotX=0,drag=false,lastX=0,lastY=0,zoom=9,entered=false,selected=null,ambientOn=false,audioCtx,osc,gain;const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORAGE,JSON.stringify(games))}function gamePosition(i){const base=[[-5.2,2.05,-4.18],[-3.1,2.05,-4.18],[-1.05,2.05,-4.18],[1.05,2.05,-4.18],[3.1,2.05,-4.18],[5.2,2.05,-4.18]];if(base[i])return base[i];const col=(i-6)%6,row=Math.floor((i-6)/6);return[-5.2+col*2.08,Math.max(.45,3.85-row*1.75),-4.18]}function rebuildGames3D(){if(!roomGroup)return;gameMeshes.forEach(g=>roomGroup.remove(g));gameMeshes=[];games.forEach((g,i)=>createGame(g,gamePosition(i)))}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),1600)}
function init3D(){scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x05070a,.055);camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);camera.position.set(0,2.5,9);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$("canvasWrap").appendChild(renderer.domElement);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();roomGroup=new THREE.Group();scene.add(roomGroup);buildRoom();addLights();addDust();bind3D();animate()}
function mat(color,rough=.7,metal=.1){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal})}function box(w,h,d,color,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);m.receiveShadow=m.castShadow=true;roomGroup.add(m);return m}
function buildRoom(){box(16,.2,12,0x0b0f14,0,-.1,0);box(16,6,.2,0x090d12,0,2.9,-5);box(.2,6,12,0x080c11,-8,2.9,0);box(.2,6,12,0x080c11,8,2.9,0);
for(let i=-7;i<=7;i+=1){const line=box(.012,.01,10,0x17222c,i,.02,0);line.material.emissive=new THREE.Color(0x101820)}for(let z=-4;z<=4;z+=1){box(14,.01,.012,0x121c24,0,.02,z)}
box(6,.12,1.4,0x151a20,0,.9,-4.65);box(6,.1,.08,0x43d9f5,0,.78,-4.05).material.emissive=new THREE.Color(0x1b6b78);
const screen=box(3.8,1.65,.08,0x07131a,0,2.5,-4.82);screen.material.emissive=new THREE.Color(0x0c4551);screen.material.emissiveIntensity=.5;
for(let i=0;i<4;i++){const shelf=box(.12,4,.6,0x161b22,-6.6+i*4.4,2.1,-4.6);box(3.5,.09,.6,0x1b2028,-4.4+i*4.4,1.2,-4.6);box(3.5,.09,.6,0x1b2028,-4.4+i*4.4,3.2,-4.6)}
games.forEach((g,i)=>createGame(g,gamePosition(i)));
for(let i=0;i<3;i++){const pedestal=box(1.2,.12,1.2,0x171c23,-3+i*3,.35,1.6);const trophy=new THREE.Mesh(new THREE.OctahedronGeometry(.42),new THREE.MeshStandardMaterial({color:i===1?0x54e7ff:0x8b6cff,metalness:.8,roughness:.18,emissive:i===1?0x123e48:0x24184a,emissiveIntensity:.5}));trophy.position.set(-3+i*3,.95,1.6);trophy.castShadow=true;roomGroup.add(trophy);trophy.userData.spin=.005+i*.002}
box(3.6,.1,1.7,0x131820,4.7,.55,2.8);box(.12,1.1,.12,0x1b222b,3.2,0,2.3);box(.12,1.1,.12,0x1b222b,6.2,0,2.3);box(.12,1.1,.12,0x1b222b,3.2,0,3.3);box(.12,1.1,.12,0x1b222b,6.2,0,3.3)}
function createGame(g,p){const group=new THREE.Group();const caseMesh=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.55,.16),new THREE.MeshStandardMaterial({color:g.color,roughness:.38,metalness:.35,emissive:new THREE.Color(g.color),emissiveIntensity:.12}));caseMesh.castShadow=true;group.add(caseMesh);const stripe=new THREE.Mesh(new THREE.BoxGeometry(.72,.035,.175),new THREE.MeshBasicMaterial({color:0xffffff}));stripe.position.y=.45;group.add(stripe);group.position.set(...p);group.userData.gameId=g.id;roomGroup.add(group);gameMeshes.push(group)}
function addLights(){scene.add(new THREE.HemisphereLight(0x6389a0,0x08090c,.55));const key=new THREE.SpotLight(0x55ddff,35,18,Math.PI/5,.55,1.5);key.position.set(0,5,4);key.target.position.set(0,1,-4);scene.add(key,key.target);const a=new THREE.PointLight(0x7655ff,18,10);a.position.set(-5,2,1);scene.add(a);const b=new THREE.PointLight(0x32d8e8,15,9);b.position.set(5,2,-1);scene.add(b)}
function addDust(){const geo=new THREE.BufferGeometry(),pts=[];for(let i=0;i<350;i++)pts.push((Math.random()-.5)*15,Math.random()*5,(Math.random()-.5)*10);geo.setAttribute("position",new THREE.Float32BufferAttribute(pts,3));const p=new THREE.Points(geo,new THREE.PointsMaterial({color:0x7195a8,size:.012,transparent:true,opacity:.45}));p.userData.dust=true;scene.add(p)}
function bind3D(){const c=renderer.domElement;c.addEventListener("pointerdown",e=>{drag=true;lastX=e.clientX;lastY=e.clientY});addEventListener("pointerup",()=>drag=false);addEventListener("pointermove",e=>{if(!drag)return;targetRotY+=(e.clientX-lastX)*.004;targetRotX=Math.max(-.12,Math.min(.16,targetRotX+(e.clientY-lastY)*.002));lastX=e.clientX;lastY=e.clientY});c.addEventListener("wheel",e=>{zoom=Math.max(5.5,Math.min(12,zoom+e.deltaY*.005))},{passive:true});c.addEventListener("click",e=>{if(Math.abs(e.clientX-lastX)>5)return;const r=c.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(gameMeshes,true);if(hits.length){let o=hits[0].object;while(o.parent&&!o.userData.gameId)o=o.parent;if(o.userData.gameId)showGame(o.userData.gameId)}});addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function animate(t=0){requestAnimationFrame(animate);if(roomGroup){roomGroup.rotation.y+=(targetRotY-roomGroup.rotation.y)*.06;roomGroup.rotation.x+=(targetRotX-roomGroup.rotation.x)*.06}camera.position.z+=(zoom-camera.position.z)*.06;scene.traverse(o=>{if(o.userData.spin)o.rotation.y+=o.userData.spin;if(o.userData.dust)o.rotation.y=t*.000015});renderer.render(scene,camera)}
function showGame(id){const g=games.find(x=>x.id===id);if(!g)return;selected=id;$("detailStatus").textContent=g.status.toUpperCase();$("detailTitle").textContent=g.title;$("detailGenre").textContent=g.genre;$("detailHours").textContent=g.hours+"h";$("detailRating").textContent=g.rating+"/10";$("detailNote").textContent=g.note;$("detail").classList.add("open");if(!$("deleteGame")){const d=document.createElement("button");d.id="deleteGame";d.className="deleteGame";d.textContent="REMOVE FROM VAULT";d.onclick=deleteSelected;$("detail").appendChild(d)}}
function renderLibrary(){const q=$("search").value.toLowerCase(),f=$("filter").value;const list=games.filter(g=>(f==="All"||g.status===f)&&(g.title+" "+g.genre).toLowerCase().includes(q));$("gameGrid").innerHTML=list.map(g=>`<article class="gameCard" data-id="${g.id}" style="--accent:#${g.color.toString(16).padStart(6,"0")}44"><small>${g.status.toUpperCase()} // ${g.hours}H</small><h3>${g.title}</h3><span>${g.genre} • ★ ${g.rating}</span></article>`).join("");document.querySelectorAll(".gameCard").forEach(c=>c.onclick=()=>{closePanels();showGame(Number(c.dataset.id))});$("gameCount").textContent=games.length+" GAMES"}
function deleteSelected(){if(!selected)return;const g=games.find(x=>x.id===selected);if(!g||!confirm("Remove "+g.title+" from your vault?"))return;games=games.filter(x=>x.id!==selected);selected=null;save();$("detail").classList.remove("open");rebuildGames3D();renderLibrary();toast("GAME REMOVED")}
function renderStats(){const total=games.reduce((n,g)=>n+g.hours,0),done=games.filter(g=>g.status==="Completed").length,avg=(games.reduce((n,g)=>n+g.rating,0)/games.length).toFixed(1);$("totalHours").textContent=total+"h";$("completed").textContent=done;$("avgRating").textContent=avg;const max=Math.max(...games.map(g=>g.hours));$("bars").innerHTML=games.map(g=>`<div class="barRow"><span>${g.title}</span><div class="bar"><i style="width:${g.hours/max*100}%"></i></div><b>${g.hours}h</b></div>`).join("")}
function closePanels(){document.querySelectorAll(".overlayPanel").forEach(p=>p.classList.remove("open"));document.querySelectorAll(".nav button").forEach(b=>b.classList.remove("active"));document.querySelector('[data-view="room"]').classList.add("active")}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".overlayPanel").forEach(p=>p.classList.remove("open"));if(b.dataset.view!=="room")$(b.dataset.view).classList.add("open");if(b.dataset.view==="stats")renderStats()});document.querySelectorAll(".panelClose").forEach(b=>b.onclick=closePanels);$("closeDetail").onclick=()=>$("detail").classList.remove("open");$("cycleStatus").onclick=()=>{if(!selected)return;const g=games.find(x=>x.id===selected),states=["Backlog","Playing","Completed"];g.status=states[(states.indexOf(g.status)+1)%3];save();showGame(selected);renderLibrary();toast("STATUS UPDATED // "+g.status.toUpperCase())};$("search").oninput=renderLibrary;$("filter").onchange=renderLibrary;$("addGameBtn").onclick=()=>$("addModal").classList.add("open");$("closeAdd").onclick=()=>$("addModal").classList.remove("open");$("addModal").onclick=e=>{if(e.target===$("addModal"))$("addModal").classList.remove("open")};$("addGameForm").onsubmit=e=>{e.preventDefault();const palette=[0x54e7ff,0x8b6cff,0xff775c,0x65e6a5,0xffc65c,0xe66ac9,0x68a8ff];games.push({id:Date.now(),title:$("newTitle").value.trim().toUpperCase(),genre:$("newGenre").value.trim(),status:$("newStatus").value,hours:Number($("newHours").value),rating:Number($("newRating").value),color:palette[games.length%palette.length],note:$("newNote").value.trim()||"Added to my personal GameVault."});save();rebuildGames3D();renderLibrary();$("addGameForm").reset();$("newHours").value=0;$("newRating").value=8;$("addModal").classList.remove("open");toast("GAME ADDED TO VAULT")};
$("enterBtn").onclick=()=>{$("intro").style.opacity=0;$("intro").style.transition=".8s";setTimeout(()=>{$("intro").remove();$("app").classList.remove("hidden");init3D();renderLibrary()},750)};
function toggleSound(){if(!ambientOn){audioCtx=new(window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();gain=audioCtx.createGain();osc.type="sine";osc.frequency.value=55;gain.gain.value=.025;osc.connect(gain);gain.connect(audioCtx.destination);osc.start();ambientOn=true;$("soundToggle").textContent="◉";toast("AMBIENCE ON")}else{gain.gain.setTargetAtTime(0,audioCtx.currentTime,.05);setTimeout(()=>osc.stop(),200);ambientOn=false;$("soundToggle").textContent="◌";toast("AMBIENCE OFF")}}$("soundToggle").onclick=toggleSound;
setTimeout(()=>{$("loading").style.opacity=0;setTimeout(()=>$("loading").remove(),600)},1250);